

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: appointment-bot-dev
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}

    volumes:
      - .:/app

    tty: true
