FROM mcr.microsoft.com/playwright/python:v1.48.0-jammy

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install debugpy
RUN playwright install --with-deps

# No source code copy → live mounted by docker-compose

CMD ["bash", "run.sh"]
